### PR TITLE
Create Dockerfile

### PR DESCRIPTION
**Pull request by jkroepke**
Add Dockerfile to run this in a docker container.

You also should be put this images to dockerhub

### CODE REVIEW

**Comment by znerol** [comment]
Thanks for the PR. Unless I'm completely mistaken this is far a way from production ready though. I see the following problems (at least):
* I seriously doubt that alpine has `pip` installed by default
* There is no reason to run the exporter as root
* I think we might want to export the port

In addition I do not trust myself that I will remember tagging and uploading a new docker image each time I release a version to pypi. Thus I only will accept a Dockerfile here if we can establish a solid automated ci pipeline which will push new image versions without human intervention.

The [node_exporter](https://github.com/prometheus/node_exporter/blob/master/Dockerfile) seems to ship with a sane Dockerfile. We might want to have a look at their workflow first.

**Comment by jkroepke** [comment]
Hi,

thanks for your feedback. Correct. I was maybe litte to quick on creating this pr, but its discussable.

Your are right. The Dockerfile is missing the EXPOSE and USER components. 

Dockerhub.com has as solid base for building images automaticly. You can continues build your master branch into a latest tag (or egde, devel, e.g.) and use git tags to create table docker tags on dockerhub. 

I still prefer the automatic build system on dockerhub over any custom provided CI build system.

**Comment by jkroepke** [comment]
> I seriously doubt that alpine has pip installed by default

Maybe alpine not. But I'm using a python baseimages which has a alpine base: `python:alpine`

IMHO the offical python base images should has always pip unless they doing some breaking changes.

**Comment by znerol** [comment]
Ok, this looks better. Will `pip install` use the code from the repository or will it fetch it from pypi?

**Comment by jkroepke** [comment]
Currently it fetch it from pypi.

It might be comming from the repository. but building the applicaton should not be done in a production ready container.

That might be interresting on node_exporters side, because they add only the already complied binary to the container. https://github.com/prometheus/node_exporter/blob/master/Dockerfile#L4

Interresting: The prometheus guys has setup a automatic build repo https://hub.docker.com/r/prom/node-exporter/ (maybe for reputation reasons?) But they build images on CircleCI.

https://github.com/prometheus/node_exporter/blob/master/circle.yml#L50 but you can do it on travis. too.

**Comment by lukasmrtvy** [comment]
Look at this https://github.com/znerol/prometheus-pve-exporter/pull/18

**Comment by znerol** [comment]
Closing in favor of #38

**Pull request closed without merging**
