### PR TITLE
Add Service Discovery using DNS to README

### PR DESCRIPTION
**Pull request by berzdev**
I've implemented this in my prometheus setup and would like to add this config to README :).

### CODE REVIEW

**Comment by znerol** [comment]
Thank you. Feel free to add this info to the [wiki](https://github.com/prometheus-pve/prometheus-pve-exporter/wiki).

I try to keep the `README` to the basics.

**Comment by berzdev** [comment]
No Problem, add this to your Wiki:
https://github.com/berzdev/prometheus-pve-exporter/wiki/Prometheus-Service-Discovery-using-DNS

Or the full source:
```
If you don't want to add your Proxmox Hostadresses in your Prometheus Configuration you can use [DNS based Service Discovery](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#dns_sd_config)

You only need a FQDN that is pointing to all Proxmox hosts, then Prometheus'll automatically detect your hosts and monitor it.
Example output from linux command `host pve-cluster-01.yr.tld` completed after DNS configuration.
```
prx.dev.berz.dev has address 192.168.1.5
prx.dev.berz.dev has address 192.168.1.6
prx.dev.berz.dev has address 192.168.1.9
```

Example Configuration in Prometheus:
```
    scrape_configs:
      - job_name: 'pve'
        dns_sd_configs:
          - names:
            - 'pve-cluster-01.yr.tld' #dns resolves multiple A records (for each host)
            type: 'A'
            port: 9221 #port is not used, this can be any integer
        metrics_path: /pve
        params:
          module: [default]
        relabel_configs:
          - source_labels: [__address__]
            target_label: __param_target
            replacement: '${1}'  # Remove port
            regex: (.+):\d+  # Regex, to get hostname/ip adress
          - source_labels: [__param_target]
            target_label: instance
          - target_label: __address__
            replacement: 127.0.0.1:9221  # PVE exporter.
```

Now Prometheus should detect all Proxmox hosts based on a DNS query.
```

**Comment by znerol** [comment]
Oh! I did not realize that the editing the wiki required team membership. I removed the restriction now. Would you mind trying to add it directly?

**Comment by berzdev** [comment]
Now it's done!

**Comment by znerol** [comment]
Thank you @berzdev

**Pull request closed without merging**
