### PR TITLE
add class ClusterReplicationCollector

### PR DESCRIPTION
**Pull request by themoriarti**
This class should collect the status of replication that is performed for each lxc/vm for all servers in the cluster.

### CODE REVIEW

**Comment by znerol** [comment]
Thanks for taking the time to file a PR.

Unfortunately scraping `/nodes` has turned out to be inherently inefficient (see #55 and #58). Especially for big and growing deployments, this can get nasty quite quickly.

This PR is using the exact same known-to-be-faulty mechanism to collect the desired data. To make matters worse, the problematic loop would be running twice after that PR landed and as a result the time to collect all metrics will double for many users.

See the comments in #115 for alternative ideas on how to scrape config efficiently.

Also note that we might scrape `/nodes` in a different manner after #164 landed.

**Comment by themoriarti** [comment]
> Thanks for taking the time to file a PR.
> 
> Unfortunately scraping `/nodes` has turned out to be inherently inefficient (see #55 and #58). Especially for big and growing deployments, this can get nasty quite quickly.
> 
> This PR is using the exact same known-to-be-faulty mechanism to collect the desired data. To make matters worse, the problematic loop would be running twice after that PR landed and as a result the time to collect all metrics will double for many users.
> 
> See the comments in #115 for alternative ideas on how to scrape config efficiently.
> 
> Also note that we might scrape `/nodes` in a different manner after #164 landed.

Yes, it really simplifies the process and speeds it up, and also makes it possible to now install the export on each of proxmox servers of the cluster and collect metrics from each server separately, but some metrics of the cluster will be duplicated. I have made changes to the process of collecting replication tasks status.

**Comment by znerol** [comment]
> but some metrics of the cluster will be duplicated. I have made changes to the process of collecting replication tasks status.

Not sure what you mean by duplicated metrics. If you have specific feedback on the refactoring, then please comment over there: #164

**Comment by znerol** [comment]
I released `3.0.0` and also merged  #198. This PR now needs a little refactoring for the new file layout.

**Comment by znerol** [comment]
Closing in favor of #243 (also credited @themoriarti over there for the original work).

**Pull request closed without merging**
