### PR TITLE
Dockerfile with entrypoint

### PR DESCRIPTION
**Pull request by lukasmrtvy**
Usage:
docker run -d --restart always --name pve -p 9221:9221 -e PVE_USER=foo -e PVE_PASSWORD=bar prometheus-pve-exporter:latest

Optional variable:
-e PVE_VERIFYSSL

You can use https://hub.docker.com/ for auto CI -> Create Automated Build -> Github -> Link and select repository -> win

### CODE REVIEW

**Comment by lukasmrtvy** [comment]
Dont worry..
hub.docker.com works as CI pipeline. You will link repository and select Dockerfile -> on every commit hub.docker.com will rebuild image and tag it (depends on branch, and if you are using releases).

You can have different Dockerfiles per Branches 

You can also compile source code in Dockerfile in multistage build and then in last stage copy builded python module (instead of installing from pip) to latest layer.. all previous are discarded.

python:alpine base image is well crafted. The best way is stick with these official images. 

My advice is to merge this PR -> setup automatic pipeline in hub.docker.com and You will see. Its pretty straightforward. Just keep proper version in Dockerfile when are You releasing new version.

**Comment by znerol** [comment]
> My advice is to merge this PR -> setup automatic pipeline in hub.docker.com and You will see. Its pretty straightforward.

I might not do that until I have clear answers to the specific questions above.

In the meantime I suggest that somebody creates a repo with the Dockerfile and sets up the build automation on his own. If that works out, I will just link to that repo from the readme.

**Comment by lukasmrtvy** [comment]
I can no help You more.

Look at this fork: https://github.com/lukasmrtvy/prometheus-pve-exporter (Dockerfile,entrypoint.sh)
Also on docker hub: https://hub.docker.com/r/lukasmrtvy/prometheus-pve-exporter/

Every time I do commit to repo, build is triggered and image is tagged as master -> dev version.
Every time I do release/tag, build is triggered and image is tagged as tag(or branch by default) -> released version.

Whole setup on hub.docker.com took 2mins.

**Comment by znerol** [comment]
Closing in favor of #38

**Pull request closed without merging**
